[DP-3153] Access UCL widget fix id names
UCL-WAMS/indigo3 pull request #96
Opened 2022-03-24 17:48 UTC by Sem-the-dev

Fixes ID names which should resolve css issue

2022-03-24 17:48 UTC, azy141 approved these changes

2022-03-24 17:58 UTC, azy141 submitted a review, later dismissed

2022-03-25 09:29 UTC, LouiseSchuller requested changes
Some of the values for fonts and sizing are in px.  This is not good practice for accessibility. All sizing values (with a few exceptions for images and small values) should be in rem. 


Information about clear left typography here

https://www.ucl.ac.uk/digital-presence/indigo3/Bartlett21/type.html

2022-03-25 11:53 UTC, LouiseSchuller approved these changes

2022-03-25 11:55 UTC, merged